# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Speaker'),
        ),
    ]
